server:
  port: 8083

spring:
  application:
    name: emergency-service

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:postgresql://localhost:5435/emergency_service_db
    username: ifortex
    password: ifortex

app:
  jwtSecret: 5d9790e5409c4ba5b52d988110ba3e63b02d60525917825c99fba26506c66c18625f6c1ad2dde820a6591851e8947e03ace8b83f6ce4e8b31248cd1d53733e6aa50b6a540f9c09a239ae1476bd04ce37126f04fe2e3b6d223e9231f6b938a6f514f2166a8e82e168062a6ed0481d292139b3a081874fe5074e9f4e8e8bce40ac
  default_radius_km: 10

